=== pallocate/tedit/users/Patricia/2019:7/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

   <xs:attribute name="id">
      <xs:simpleType>
         <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="281474976710655"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <!--xs:element name="name">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="32"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element>
   <xs:element name="desc">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:minLength value="0"/>
            <xs:maxLength value="256"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:element-->

   <xs:attribute name="change">
      <xs:simpleType>
         <xs:restriction base="xs:integer">
            <xs:minInclusive value="-10000"/>
            <xs:maxInclusive value="10000"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <xs:attribute name="amount">
      <xs:simpleType>
         <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <xs:attribute name="prefix">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:enumeration value="None"/>
            <xs:enumeration value="Exa"/>
            <xs:enumeration value="Peta"/>
            <xs:enumeration value="Tera"/>
            <xs:enumeration value="Giga"/>
            <xs:enumeration value="Mega"/>
            <xs:enumeration value="Kilo"/>
            <xs:enumeration value="Hecto"/>
            <xs:enumeration value="Deca"/>
            <xs:enumeration value="Deci"/>
            <xs:enumeration value="Centi"/>
            <xs:enumeration value="Milli"/>
            <xs:enumeration value="Micro"/>
            <xs:enumeration value="Nano"/>
            <xs:enumeration value="Pico"/>
            <xs:enumeration value="Femto"/>
            <xs:enumeration value="Atto"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <xs:attribute name="unit">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:enumeration value="None"/>
            <xs:enumeration value="Piece"/>
            <xs:enumeration value="Gram"/>
            <xs:enumeration value="Litre"/>
            <xs:enumeration value="Second"/>
            <xs:enumeration value="Watt"/>
            <xs:enumeration value="Metre"/>
            <xs:enumeration value="Metre square"/>
            <xs:enumeration value="Metre cubic"/>
            <xs:enumeration value="Tonne"/>
            <xs:enumeration value="Hectare"/>
            <xs:enumeration value="Joule"/>
            <xs:enumeration value="Calorie"/>
            <xs:enumeration value="Minute"/>
            <xs:enumeration value="Hour"/>
            <xs:enumeration value="Day"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <xs:attribute name="price">
      <xs:simpleType>
         <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="281474976710655"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <xs:attribute name="sensetive">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <xs:attribute name="analogue">
      <xs:simpleType>
         <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
         </xs:restriction>
      </xs:simpleType>
   </xs:attribute>

   <xs:element name="product">
      <xs:complexType>
         <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="product"/>
         </xs:sequence>
         <xs:attribute ref="id" use="required"/>
         <xs:attribute name="name" type="xs:string"/>
         <xs:attribute name="desc" type="xs:string"/>
         <xs:attribute ref="amount"/>
         <xs:attribute ref="prefix"/>
         <xs:attribute ref="unit"/>
         <xs:attribute ref="change"/>
         <xs:attribute ref="price"/>
         <xs:attribute ref="sensetive"/>
         <xs:attribute ref="analogue"/>
      </xs:complexType>
   </xs:element>

</xs:schema>

=== pallocate/tedit/users/Patricia/2020:1/consumption.xml
<?xml version="1.0" encoding="utf-8"?>
<product desc="Anything in the economy." id="100035" name="Product" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">

   <product id="101000" name="Public">

      <product id="83101800" name="Electricity" desc="Electric power" prefix="kilo" unit="joule" price="35" />
      <product id="83101500" name="Water and sewer" desc="Water and sewer utilities" price="0" />
      <product id="78100000" name="Transport" desc="Hub system, logistic" prefix="kilo" unit="metre" price="112" />
      <product id="85101500" name="Medical care" desc="Healthcare center" unit="hour" price="0" />
      <product id="91111600" name="Personal assistance" desc="Personal assistance and care" unit="hour" />
      <product id="83121702" name="Radio DIY" desc="Radio service" price="0" />
      <product id="10171504" name="Compost" desc="Composted organic materials" prefix="kilo" unit="gram" price="15" />

   </product>

   <product id="102000" name="Basic">

      <product id="50001000" name="Materials">
         <product id="11121710" name="Charcoal" desc="Charcoal fuel" unit="tonne" price="120000" />
         <product id="15111500" name="Wood gas" desc="Gaseous fuel" unit="metre_3" price="90000" />
         <product id="30000000" name="Plank" desc="Construction material" unit="metre" price="50" />
         <product id="11121707" name="Insulation" desc="Wood wool" unit="bale" price="200" />
         <product id="14110000" name="Paper" desc="Paper roll" unit="piece" price="1700" />
         <product id="11161805" name="Velvet textile" desc="Synthetic velvet" unit="metre" price="30" />
         <product id="11162300" name="Leather" desc="Leather material" unit="metre_2" price="660" />
         <product id="11161600" name="Wool" desc="Wool textile" unit="metre" price="60" />
      </product>

      <product id="50001000" name="Food">
         <product id="50101538" name="Vegetables" desc="Vegetable crops" analogue="true" prefix="kilo" unit="gram" price="65" change="-15">
            <product id="50101502" name="Potatoes" desc="Freash potatoes" prefix="kilo" unit="gram" price="65" change="-15" />
            <product id="50101503" name="Cabbage" desc="Freash cabbage" prefix="kilo" unit="gram" price="65" change="-15" />
            <product id="50101504" name="Pumpkins" desc="Freash pumpkins" prefix="kilo" unit="gram" price="65" change="-15" />
         </product>
         <product id="50111000" name="Meat" desc="Freash meat">
            <product id="50111512" name="Pig" desc="Freash pig meat" prefix="kilo" unit="gram" price="300" />
            <product id="50111513" name="Cheep" desc="Freash cheep meat" prefix="kilo" unit="gram" price="400" />
         </product>
         <product id="50001001" name="Other">
            <product id="50221100" name="Flour" desc="Ground cereal, silted" prefix="kilo" unit="gram" price="40" />
            <product id="50121500" name="Fish" desc="Freash fish, filed" prefix="kilo" unit="gram" price="960" />
            <product id="50101541" name="Mushrooms" desc="Freash mushrooms" prefix="kilo" unit="gram" price="200" />
         </product>
      </product>

   </product>

   <product id="103000" name="Derived">
      <product id="55101500" name="News paper" desc="Printed publication" unit="piece" price="40" />
      <product id="27112005" name="Axe" desc="Sharp axe" unit="piece" price="800" />
      <product id="27112002" name="Spade" desc="Digging spade" unit="piece" price="1000" />
      <product id="21101504" name="Weeder" desc="Agricultural machinery" unit="piece" price="100000" />
      <product id="50181901" name="Bread" desc="Fresh bread loaf" unit="piece" price="75" />
      <product id="50182001" name="Pumpkin pie" desc="Fruit pie" unit="piece" price="100" />
      <product id="53101500" name="Trousers" desc="Unisex trousers" unit="piece" price="500" />
      <product id="53101604" name="Blous" desc="Velvet blous" unit="piece" price="450" />
      <product id="53103000" name="Tshirt" desc="Standard Tshirt" unit="piece" price="400" />
      <product id="56101515" name="Bed" desc="Rattan bed" unit="piece" price="15000" />
      <product id="56101519" name="Table" desc="Birch wood table" unit="piece" price="5000" />
      <product id="43171800" name="Laptop" desc="Computer hardware" unit="piece" price="25000" />
      <product id="34101009" name="Mobile" desc="Mobile telephone" unit="piece" price="15000" />
      <product id="25101600" name="Truck" desc="Cargo vehicle" unit="piece" price="1250000" />
      <product id="25101500" name="Bus" desc="Passenger vehicles" unit="piece" price="1000000" />
   </product>

   <product id="104000" name="Services">
      <product id="91100000" name="Hair cut" desc="Personal appearance" price="700" />
      <product id="72100000" name="Repairs" desc="Repairs and maintenance" unit="hour" price="1400" />
      <product id="90101500" name="Restaurant meal" desc="Eating and drinking establishment" price="1000" />
   </product>

</product>

=== pallocate/tedit/users/David/2021:1/8.xml
<?xml version="1.0" encoding="utf-8"?>
<product desc="Anything in the economy." id="100035" name="Product" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">

   <product id="101000" name="Utility">
      <product id="83101800" name="Electricity" desc="Electric power" prefix="kilo" unit="joule" price="35" />
      <product id="78100000" name="Transport" desc="Hub system, logistic" prefix="kilo" unit="gram" price="112" />
      <product id="85101500" name="Medical care" desc="Hospital" unit="hour" price="0" />
   </product>

   <product id="102000" name="Basic">
      <product id="50001000" name="Materials">
         <product id="11121710" name="Charcoal" desc="Charcoal fuel" unit="tonne" price="95000" />
         <product id="30000000" name="Plank" desc="Construction material" unit="metre" price="50" />
         <product id="14110000" name="Paper" desc="Paper roll" unit="piece" price="1700" />
         <product id="11161805" name="Rayon" desc="Rayon textile" unit="metre" price="30" />
         <product id="11162300" name="Leather" desc="Leather material" unit="metre_2" price="460" />
         <product id="11161600" name="Wool textile" desc="Wool textile" unit="metre" price="60" />
      </product>

      <product id="50001000" name="Food">

         <product id="50101538" name="Vegetables" desc="Vegetable crops" analogue="true" prefix="kilo" unit="gram" price="65" change="-15">
            <product id="50101502" name="Potatoes" desc="Potatoes" prefix="kilo" unit="gram" price="65" change="-15" />
            <product id="50101503" name="Cabbage" desc="Cabbage" prefix="kilo" unit="gram" price="65" change="-15" />
            <product id="50101504" name="Pumpkins" desc="Pumpkins" prefix="kilo" unit="gram" price="65" change="-15" />
         </product>
         <product id="50111000" name="Meat" desc="Freash meat">
            <product id="50111512" name="Pork" desc="Pork meat" prefix="kilo" unit="gram" price="300" />
            <product id="50111513" name="Cheep" desc="Cheep meat" prefix="kilo" unit="gram" price="400" />
            <product id="50111514" name="Beef" desc="Beef meat" prefix="kilo" unit="gram" price="600" />
         </product>
         <product id="50001001" name="Other">
            <product id="50221100" name="Flour" desc="Silted ground cereal" prefix="kilo" unit="gram" price="40" />
            <product id="50121500" name="Fish" desc="Freash fish" prefix="kilo" unit="gram" price="260" />
            <product id="50101541" name="Mushrooms" desc="Freash mushrooms" prefix="kilo" unit="gram" price="200" />
         </product>

      </product>
   </product>

   <product id="103000" name="Derived">
      <product id="55101504" name="News paper" desc="Printed publication" unit="piece" price="40" />
      <product id="27112005" name="Axe" desc="Sharp axe" unit="piece" price="800" />
      <product id="27112002" name="Spade" desc="Digging spade" unit="piece" price="850" />
      <product id="50181901" name="Bread" desc="A fresh bread" unit="piece" price="75" />
      <product id="50182001" name="Pumpkin pie" desc="A pumpkin pie" unit="piece" price="100" />
      <product id="53101500" name="Trousers" desc="Q-Design, trousers" unit="piece" price="500" />
      <product id="53101604" name="Blous" desc="Q-Design, blous" unit="piece" price="450" />
      <product id="53103000" name="Sweater" desc="Q-Design, sweater" unit="piece" price="400" />
      <product id="56101515" name="Bed" desc="A wooden bed " unit="piece" price="10000" />
      <product id="56101519" name="Table" desc="Birch wood table" unit="piece" price="5000" />
   </product>

   <product id="104000" name="Services" analogue="true" unit="hour" price="950">
      <product id="91100000" name="Hair cut" desc="A hair cut at the barber" unit="hour" price="950" />
      <product id="72100000" name="Repairs" desc="Repairs and maintenance" unit="hour" price="950" />
      <product id="90101500" name="Restaurant meal" desc="A meal at the restaurant"  unit="hour" price="950" />
   </product>

</product>

=== pallocate/tedit/users/Patricia/2020:1/production.xml
<?xml version="1.0" encoding="utf-8"?>
<product desc="Any job" id="100001" name="Job" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">

    <product id="5" name="BBA Cables" desc="Work at BBA Cables">
        <product id="73120000" name="Machine operator" desc="High power cable machine operator" amount="1.0" unit="Hour" price="650"/>
    </product>

    <product id="1" name="University" desc="Formosa heights university">
        <product id="86121721" name="Design" desc="Design studies" amount="1.0" unit="Hour" price="20"/>
        <product id="86121715" name="Math studies" desc="University studies, level three mathematics" amount="1.0" unit="Hour" price="125"/>
    </product>

    <product desc="The Farmland cooperative" id="7" name="Farmland coop">
        <product id="70140000" name="Weeding" desc="Crop production and management and protection" amount="1.0" unit="Hour" price="400"/>
        <product id="70130001" name="Compost manager" desc="Managing the compost operation" amount="1.0" unit="Hour" price="25"/>
        <product id="70130000" name="Earth works" desc="Land and soil preparation and management and protection" amount="1.0" unit="Hour" price="255"/>
    </product>

</product>

=== pallocate/tedit/users/David/2020:1/production.xml
<?xml version="1.0" encoding="utf-8"?>
<product desc="Any job" id="100001" name="Job" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">

   <product id="1" name="University" desc="Formosa heights university">
      <product id="86121751" name="Physics and math teaching" desc="Teaching university physics and mathematics" amount="1.0" unit="Hour" price="150"/>
   </product>

   <product id="6" name="Hospital" desc="Formosa heights Hospital">
      <product id="76110000" name="Cleaning" desc="Hospital cleaning and sterilization" amount="1.0" unit="Hour" price="900"/>
   </product>

   <product id="7" name="Farmland coop" desc="The Farmland cooperative">
      <product id="77100000" name="Ecosystem design" desc="Permaculture design project" amount="1.0" unit="Hour" price="22"/>
      <product id="81150000" name="Ecological improvements" desc="Improving resource flows project" amount="1.0" unit="Hour" price="31"/>
   </product>

</product>

=== pallocate/tedit/users/Bob/2020:1/Consumption/Consumption.xml
<?xml version="1.0" encoding="utf-8"?>
<product desc="Anything in the economy." id="100035" name="Product"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">
    <product id="50000000" name="Food">
        <product amount="1" analogue="true" desc="Milk" down="15"
            id="50131700" name="Milk" price="14" unit="Litre" up="15">
            <product amount="1" desc="Nice and creamy!" id="150131700"
                name="LindaÂ´s Creamy milk" unit="Litre"/>
            <product amount="1" desc="Milk" id="250131700"
                name="HIC coop" unit="Litre"/>
        </product>
        <product desc="Chicken eggs" down="5" id="150131600" name="Eggs"
            price="32" unit="Piece" up="4"/>
    </product>
    <product id="78000000" name="Transport">
        <product desc="Transports people and cargo" id="178101800"
            name="Formosa Heights Taxi" prefix="Kilo" price="112" unit="Metre"/>
    </product>
</product>

=== pallocate/tedit/users/Patricia/2020:7/consumption.xml
<?xml version="1.0" encoding="utf-8"?>
<product desc="Anything in the economy." id="100035" name="Product" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">

   <product id="101000" name="Public">

      <product id="83101800" name="Electricity" desc="Electric power" prefix="Kilo" unit="Juole" price="35" />
      <product id="83101500" name="Water and sewer" desc="Water and sewer utilities" unit="Metre_3" price="0" />
      <product id="78100000" name="Transport" desc="Hub system, logistic" prefix="Kilo" unit="Metre" price="112" />
      <product id="85101500" name="Medical care" desc="Healthcare center" unit="Hour" price="0" />
      <product id="91111600" name="Personal assistance" desc="Personal assistance and care" unit="Hour" price="0" />
      <product id="83121702" name="Radio DIY" desc="Radio service" price="0" />
      <product id="10171504" name="Compost" desc="Composted organic materials" />

   </product>

   <product id="102000" name="Basic">

      <product id="50001000" name="Materials">
         <product id="11121710" name="Charcoal" desc="Charcoal fuel" unit="Tonne" />
         <product id="15111500" name="Wood gas" desc="Gaseous fuel" unit="Metre_3" />
         <product id="30000000" name="Plank" desc="Construction material" unit="Metre" />
         <product id="11121707" name="Insulation" desc="Wood wool bale" unit="Piece" />
         <product id="14110000" name="Paper" desc="Paper roll" unit="Piece" />
         <product id="11161805" name="Velvet textile" desc="Synthetic velvet" unit="Metre" />
         <product id="11162300" name="Leather" desc="Leather material" unit="Metre" />
         <product id="11161600" name="Wool" desc="Wool textile" unit="Metre" />
      </product>

      <product id="50001000" name="Food">
         <product id="50101538" name="Vegetables" analogue="true" price="80" desc="Vegetable crops" prefix="kilo" unit="gram" change="15">
            <product id="50101502" name="Potatoes" desc="Freash potatoes" prefix="kilo" unit="gram" />
            <product id="50101503" name="Cabbage" desc="Freash cabbage" prefix="kilo" unit="gram" />
            <product id="50101504" name="Pumpkins" desc="Freash pumpkins" prefix="kilo" unit="gram" />
         </product>
         <product id="50111000" name="Meat" analogue="true" price="250" prefix="kilo" unit="gram" change="15">
            <product name="Pig" desc="Freash pig meat" id="50111512" prefix="kilo" unit="gram" />
            <product name="Cheep" desc="Freash cheep meat" id="50111513" prefix="kilo" unit="gram" />
         </product>
         <product id="50001001" name="Other">
            <product name="Flour" desc="Cereal product" id="50221100" prefix="kilo" unit="gram" />
            <product name="Fish" desc="Freash fish" id="50121500" prefix="kilo" unit="gram" />
            <product name="Mushrooms" desc="Freash mushrooms" id="50101541" prefix="kilo" unit="gram" />
         </product>
      </product>

   </product>

   <product id="103000" name="Derived">
      <product id="55101500" name="News paper" desc="Printed publication" unit="Piece" price="60" />
      <product id="27112005" name="Axe" desc="Sharp axe" unit="Piece" />
      <product id="27112002" name="Spade" desc="Digging spade" unit="Piece" />
      <product id="21101504" name="Weeder" desc="Agricultural machinery" ssunit="Piece" />
      <product id="50181901" name="Bread" desc="Fresh bread loaf" unit="Piece" />
      <product id="50182001" name="Apple pie" desc="Fruit pie" unit="Piece" />
      <product id="53101500" name="Trousers" desc="Unisex trousers" unit="Piece" />
      <product id="53101604" name="Blous" desc="Velvet blous" unit="Piece" />
      <product id="53103000" name="Tshirt" desc="Standard Tshirt" unit="Piece" />
      <product id="56101515" name="Bed" desc="Rattan bed" unit="Piece" />
      <product id="56101519" name="Table" desc="Birch wood table" unit="Piece" />
      <product id="43171800" name="Laptop" desc="Computer hardware" unit="Piece" />
      <product id="34101009" name="Mobile" desc="Mobile telephone" unit="Piece" />
      <product id="25101600" name="Truck" desc="Cargo vehicle" unit="Piece" price="950000" />
      <product id="25101500" name="Bus" desc="Passenger vehicles" unit="Piece" price="800000" />
   </product>

   <product id="104000" name="Services">
      <product id="91100000" name="Hair cut" desc="Personal appearance" />
      <product id="72100000" name="Repairs" desc="Repairs and maintenance" />
      <product id="90101500" name="Restaurant" desc="Eating and drinking establishment" />
   </product>

</product>

=== pallocate/tedit/users/David/2021:1/1.xml
<?xml version="1.0" encoding="utf-8"?>
<product desc="" id="100001" name="Job" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="products.xsd">

   <product id="1" name="University" desc="Formosa heights university">
      <product id="86121701" name="Education preparation" desc="Preparation of educational material and pedagogy" amount="1.0" unit="Hour" price="350"/>
      <product id="86121702" name="Physics and math teaching" desc="Teaching university physics and mathematics" amount="1.0" unit="Hour" price="150"/>
      <product id="86121703" name="Student counceling" desc="Student counceling individually and in group." amount="1.0" unit="Hour" price="300"/>
      <product id="86121705" name="Cleaning work" desc="Cleaning, dish washing, floors etc." amount="1.0" unit="Hour" price="850"/>
      <product id="86121706" name="School maintenance" desc="Practical maintenance, fixing simpler problems, mowin lawn" amount="1.0" unit="Hour" price="300"/>
      <product id="94100001" name="Meetings" desc="Council meetings." amount="1.0" unit="Hour" price="150"/>
   </product>

</product>
